base-config:
  company: Alibaba
  open_source: false
  supports:
    temperature: true
  metadata:
    available_for_everyone: false
    available_as_evaluator: false
  default_parameters:
    temperature: 0.7
  properties:
    reasoning_model: false

qwen-3-vl-models:
  base-config:
    supports:
      images: true

  alibaba/qwen3-vl-plus-2025-09-23:
    label: Qwen 3 VL Plus
    open_source: true
    description: Qwen 3 VL Plus (2025-09-23)
    release_date: 2025-09-23
    metadata:
      deprecated: true
    properties:
      context_window: 262_144
      max_tokens: 32_768
      training_cutoff: ""
      reasoning_model: false
    costs_per_million_token:
      input: 0.2
      output: 1.6

qwen-3-max-models:
  base-config:
    supports:
      tools: true
      images: false
    # only applies for <32K input tokens
    # TODO: add thresholds
    costs_per_million_token:
      input: 1.2
      output: 6.0

  alibaba/qwen3-max-2026-01-23:
    label: Qwen 3 Max Thinking
    description: Qwen 3 Max with enhanced reasoning capabilities
    release_date: 2026-01-23
    properties:
      context_window: 256_000
      max_tokens: 32_000
      reasoning_model: true

  alibaba/qwen3-max-preview:
    label: Qwen 3 Max Preview
    description: Preview of the largest and most recent Qwen Model
    release_date: 2025-09-05
    properties:
      context_window: 262_144
      max_tokens: 65_536
      reasoning_model: true

  alibaba/qwen3-max-2025-09-23:
    label: Qwen 3 Max 2025-09-23
    description: Largest and most recent Qwen Model
    release_date: 2025-09-23
    properties:
      context_window: 262_144
      max_tokens: 65_536
      training_cutoff: ""
      reasoning_model: true

  alibaba/qwen3-max:
    label: Qwen 3 Max
    description: Largest and most recent Qwen Model
    release_date: 2025-09-23
    properties:
      context_window: 262_144
      max_tokens: 65_536
      training_cutoff: ""
      reasoning_model: false

qwen-3.5-plus-models:
  base-config:
    supports:
      images: true
      videos: true
      tools: true
    costs_per_million_token:
      input: 0.4
      output: 2.4
      cache:
        read: 0.04
        write: 0.5
      context:
        threshold: 256_000
        input: 1.2
        output: 7.2
        cache:
          read: 0.12
          write: 1.5

  alibaba/qwen3.5-plus:
    label: Qwen 3.5 Plus
    open_source: true
    description: Hosted Qwen3.5-397B-A17B â€” native multimodal model for agentic AI
    documentation_url: https://www.alibabacloud.com/help/en/model-studio/getting-started/models
    release_date: 2026-02-16
    properties:
      context_window: 991_000
      max_tokens: 65_536
      reasoning_model: false
    alternative_keys:
      - alibaba/qwen3.5-plus-thinking:
          properties:
            reasoning_model: true
          default_parameters:
            temperature: 0.6 # from https://huggingface.co/Qwen/Qwen3.5-397B-A17B