base-config:
  company: DeepSeek
  documentation_url: https://api-docs.deepseek.com/
  open_source: true
  supports:
    images: false
    files: false
  metadata:
    available_as_evaluator: false
    available_for_everyone: true
    ignored_for_cost: false
  properties:
    reasoning_model: false
    
deepseek-endpoints:
  base-config:
    supports:
      images: false
      files: false
      tools: true
      batch: false
      temperature: true
    default_parameters:
      temperature: 1
    costs_per_million_token:
      input: 0.28
      output: 0.42
      cache:
        read_discount: 0.1

  deepseek/deepseek-chat:
    label: DeepSeek Chat
    description: DeepSeek's latest chat model
    release_date: 2025-09-29
    properties:
      context_window: 128_000
      max_tokens: 8_000
      reasoning_model: false

  deepseek/deepseek-reasoner:
    label: DeepSeek Reasoner
    description: DeepSeek's latest reasoning model
    release_date: 2025-09-29
    properties:
      context_window: 128_000
      max_tokens: 64_000
      reasoning_model: true
