base-config:
  company: Inception
  documentation_url: https://docs.inceptionlabs.ai/get-started/models
  open_source: false
  supports:
    images: false
    tools: true
    files: false
  metadata:
    available_as_evaluator: false
    available_for_everyone: true
    ignored_for_cost: false

inception-models:
  inception/mercury:
    label: Mercury
    release_date: 2025-11-06
    properties:
      reasoning_model: false
      context_window: 128_000
      max_tokens: 16_384 # rounded down
    costs_per_million_token:
      input: 0.25
      output: 1