base-config:
  company: Mistral
  documentation_url: https://docs.mistral.ai/getting-started/models/models_overview/
  open_source: false
  supports:
    images: false
    files: false
    tools: true
  metadata:
    available_as_evaluator: false
    available_for_everyone: true
    ignored_for_cost: false
  properties:
    context_window: null
    max_tokens: null
    training_cutoff: null

magistral-models:
  base-config:
    properties:
      reasoning_model: true
    supports:
      temperature: true
    default_parameters:
      temperature: 0.7

  mistralai/magistral-medium-2506:
    label: Magistral Medium 1.0 (06/2025)
    description: Magistral Medium 2506
    documentation_url: https://mistral.ai/news/magistral
    release_date: 2025-06-10
    properties:
      context_window: 131_072
      max_tokens: 40_000
      training_cutoff: "2024-05"
    supports:
      images: true
    costs_per_million_token:
      input: 2
      output: 5

  mistralai/magistral-medium-2509:
    label: Magistral Medium 1.2 (09/2025)
    description: Reasoning model with vision support released in September 2025.
    release_date: 2025-09-18
    properties:
      context_window: 128_000
      max_tokens: 128_000
    supports:
      images: true
    costs_per_million_token:
      input: 2
      output: 5

  mistralai/magistral-small-2509:
    label: Magistral Small 1.2 (09/2025)
    open_source: true
    description: Small reasoning model with vision support released in September 2025.
    release_date: 2025-09-18
    properties:
      context_window: 128_000
      max_tokens: 128_000
    supports:
      images: true
    costs_per_million_token:
      input: 0.5
      output: 1.5

# Standard Mistral Models
mistralai-models:
  base-config:
    properties:
      reasoning_model: false
      max_tokens: 256_000
    supports:
      temperature: true
    default_parameters:
      temperature: 0.7

  mistralai/mistral-large-2512:
    label: Mistral Large 3
    description: Mistral's latest flagship model
    release_date: 2025-12-02
    open_source: true
    properties:
      context_window: 256_000
      max_tokens: 256_000
    supports:
      images: true
      tools: true
    costs_per_million_token:
      input: 0.5
      output: 1.5
    default_parameters:
      temperature: 0.065

  mistralai/devstral-2512:
    label: Devstral 2
    description: Enterprise grade coding model that excels at using tools to explore codebases and power software engineering agents.
    documentation_url: https://docs.mistral.ai/models/devstral-2-25-12
    release_date: 2025-12-09
    open_source: true
    properties:
      context_window: 256_000
      max_tokens: 256_000
    supports:
      images: false
      tools: true
    costs_per_million_token:
      input: 0.4
      output: 2.0
    default_parameters:
      temperature: 0.2

  mistralai/labs-devstral-small-2512:
    label: Devstral Small 2
    description: Open source coding model that excels at using tools to explore codebases and power software engineering agents.
    documentation_url: https://docs.mistral.ai/models/devstral-small-2-25-12
    release_date: 2025-12-09
    open_source: true
    properties:
      context_window: 256_000
      max_tokens: 256_000
    supports:
      images: false
      tools: true
    costs_per_million_token:
      input: 0.1
      output: 0.3
    default_parameters:
      temperature: 0.2

  mistralai/mistral-medium-2505:
    label: Mistral Medium 3.1 (05/2025)
    description: Mistral Medium 2505
    documentation_url: https://mistral.ai/news/mistral-medium-3
    release_date: 2025-05-07
    properties:
      context_window: 131_072
      max_tokens: 32768
      training_cutoff: "2024-05"
    supports:
      images: true
    costs_per_million_token:
      input: 0.4
      output: 2.0

  mistralai/mistral-small-2503:
    label: Mistral Small 3.1 (03/2025)
    description: Mistral Small 2503
    documentation_url: https://mistral.ai/news/mistral-small-3-1
    release_date: 2025-03-17
    properties:
      context_window: 131_072
      max_tokens: 8192
      training_cutoff: "2024-05"
    supports:
      images: true
    costs_per_million_token:
      input: 0.075
      output: 0.3

  mistralai/pixtral-large-2411:
    label: Pixtral Large (11/2024)
    description: Latest version of the Pixtral Large model.
    release_date: 2024-11-18
    properties:
      context_window: 128_000
    supports:
      images: true
    metadata:
      deprecated: true
    costs_per_million_token:
      input: 2.00
      output: 6.00

  mistralai/mistral-large-2411:
    label: Mistral Large (11/2024)
    description: Latest version of the Mistral Large model.
    release_date: 2024-11-18
    properties:
      context_window: 128_000
    metadata:
      deprecated: true
    costs_per_million_token:
      input: 2.00
      output: 6.00

  mistralai/mistral-small-2402:
    label: Mistral Small (02/2024)
    description: Latest version of the Mistral Small model.
    release_date: 2024-09-17
    properties:
      context_window: 32_000
    metadata:
      deprecated: true
    costs_per_million_token:
      input: 0.20
      output: 0.60
