base-config:
  company: zAI
  open_source: true
  documentation_url: https://docs.z.ai/
  supports:
    images: false
    files: false
    temperature: true
    tools: true
  properties:
    reasoning_model: true
  default_parameters:
    temperature: 0.6
    top_p: 1
  costs_per_million_token:
    cache:
      read_discount: 1
      write_markup: 1

glm-5-models:
  zai/glm-5:
    label: GLM 5
    description: "z.AI flagship model"
    release_date: 2026-02-11
    costs_per_million_token: # guessing!!!
      input: 1
      output: 3.2
      cache:
        read: 0.2
    properties:
      reasoning_model: false
      context_window: 200_000
      max_tokens: 131_072
    default_parameters:
      temperature: 1
      top_p: 0.95
    alternative_keys:
      - zai/glm-5-thinking:
          properties:
            reasoning_model: true
          provider_properties:
            clear_thinking: false


glm-4-models:
  zai/glm-4.7-flashx:
    label: GLM 4.7 Flash
    description: "z.AI lightweight fast model"
    release_date: 2026-01-19
    properties:
      context_window: 200_000
      max_tokens: 128_000
    costs_per_million_token:
      input: 0.07
      output: 0.4
      cache:
        read: 0.01
    default_parameters:
      # from https://huggingface.co/zai-org/GLM-4.7-Flash
      temperature: 1
      top_p: 0.95
    provider_properties:
      clear_thinking: false
  
  zai/glm-4.7:
    label: GLM 4.7
    description: "Latest model from ZAI"
    release_date: 2025-12-22
    properties:
      context_window: 200_000
      max_tokens: 128_000
    costs_per_million_token:
      input: 0.6
      output: 2.2
      cache:
        read: 0.11
    default_parameters:
      temperature: 1
    alternative_keys:
      - vercel/zai/glm-4.7

  zai/glm-4.5:
    label: GLM 4.5
    description: "z.AI old model"
    release_date: 2025-07-28
    properties:
      context_window: 128_000
      max_tokens: 81_920
    costs_per_million_token:
      input: 0.6
      output: 2.2
      cache:
        read: 0.11
    alternative_keys:
      - fireworks/glm-4p5:
          metadata:
            deprecated: true
          costs_per_million_token:
            input: 0.55
            output: 2.19

  zai/glm-4.5-air:
    label: GLM 4.5 Air
    description: "z.AI lightweight model"
    release_date: 2025-07-28
    properties:
      context_window: 128_000
      max_tokens: 81_920
    costs_per_million_token:
      input: 0.2
      output: 1.1
      cache:
        read: 0.03
    alternative_keys:
      - together/zai-org/GLM-4.5-Air-FP8:
        costs_per_million_token:
          input: 0.22
          output: 0.88

  zai/glm-4.6:
    label: GLM 4.6
    description: "z.AI flagship model"
    release_date: 2025-09-30
    properties:
      context_window: 200_000
      max_tokens: 122_880
    costs_per_million_token:
      input: 0.6
      output: 2.2
      cache:
        read: 0.11
    alternative_keys:
      - fireworks/glm-4p6:
        costs_per_million_token:
          input: 0.55
          output: 2.19
