base-config:
  company: zAI
  open_source: true
  documentation_url: https://docs.z.ai/
  supports:
    images: false
    files: false
    temperature: true
    tools: true
  properties:
    reasoning_model: true
  default_parameters:
    temperature: 0.6
    top_p: 1
  costs_per_million_token:
    cache:
      read_discount: 1
      write_markup: 1

zai-models:
  zai/glm-4.5:
    label: GLM 4.5
    description: "z.AI old model"
    release_date: 2025-07-28
    properties:
      context_window: 128_000
      max_tokens: 81_920
    costs_per_million_token:
      input: 0.6
      output: 2.2
      cache:
        read: 0.11
    alternative_keys:
      - fireworks/glm-4p5:
        costs_per_million_token:
          input: 0.55
          output: 2.19

  zai/glm-4.5-air:
    label: GLM 4.5 Air
    description: "z.AI lightweight model"
    release_date: 2025-07-28
    properties:
      context_window: 128_000
      max_tokens: 81_920
    costs_per_million_token:
      input: 0.2
      output: 1.1
      cache:
        read: 0.03
    alternative_keys:
      - together/zai-org/GLM-4.5-Air-FP8:
        costs_per_million_token:
          input: 0.22
          output: 0.88

  zai/glm-4.6:
    label: GLM 4.6
    description: "z.AI flagship model"
    release_date: 2025-09-30
    properties:
      context_window: 200_000
      max_tokens: 122_880
    costs_per_million_token:
      input: 0.6
      output: 2.2
      cache:
        read: 0.11
    alternative_keys:
      - fireworks/glm-4p6:
        costs_per_million_token:
          input: 0.55
          output: 2.19
